# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaiwanGoGoGo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaiwanGoGoGo
	pod 'RxSwift', '~> 5.1.1'
        pod 'RxCocoa', '~> 5.1.1'
        pod 'ObjectMapper'
        pod 'Moya/RxSwift', '~> 14.0'
        pod 'Kingfisher', '~> 5.7.1'
end
